name: supabase_auth_ui
description: UI library to implement auth forms using Supabase and Flutter
version: 0.5.5
homepage: https://supabase.com
repository: 'https://github.com/supabase-community/flutter-auth-ui'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.6
  email_validator: ^2.0.1
  font_awesome_flutter: ^10.6.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.0
  crypto: ^3.0.3
  mime: ^2.0.0
  image_picker: ^1.1.2
  ui_avatar: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/logos/

screenshots:
  - description: Supabase Auth UI
    path: screenshots/supabase_auth_ui.png
