name: supabase_auth_ui
description: UI library to implement auth forms using Supabase and Flutter
version: 0.4.0
homepage: https://supabase.com
repository: 'https://github.com/supabase-community/flutter-auth-ui'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.0.1
  email_validator: ^2.0.1
  font_awesome_flutter: ^10.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/logos/

screenshots:
  - description: Supabase Auth UI
    path: screenshots/supabase_auth_ui.png
