name: supabase_auth_ui
description: UI library to implement auth forms using Supabase and Flutter
version: 0.0.1-dev.3
homepage: https://supabase.com
repository: 'https://github.com/supabase-community/flutter-auth-ui'

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^1.0.0-dev.3
  email_validator: ^2.0.1
  font_awesome_flutter: ^9.0.0-nullsafety
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
