name: supabase_auth_ui
description: UI library to implement auth forms using Supabase and Flutter
version: 0.2.1
homepage: https://supabase.com
repository: 'https://github.com/supabase-community/flutter-auth-ui'

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^1.4.0
  email_validator: ^2.0.1
  font_awesome_flutter: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/logos/google_light.png
